services:
  - type: web
    name: nextskill
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nextskill-db
          property: connectionString

databases:
  - name: nextskill-db
    databaseName: nextskill
    user: nextskill
